const dashboardCharts = [
  {
    section: 'shipping',
    title: 'Transit through the Strait of Hormuz',
    id: 'datawrapper-chart-CtUz4',
    src: 'https://datawrapper.dwcdn.net/CtUz4',
    meta: [{ label: 'Transits', value_name: 'transits' }],
    seriesKey: 'seriesTransit',
    frequency: 'Daily',
  },
  {
    section: 'shipping',
    title: 'Cost of marine fuel',
    id: 'datawrapper-chart-nK6Hr',
    src: 'https://datawrapper.dwcdn.net/nK6Hr',
    meta: [
      { label: 'High sulphur', value_name: 'highsulfur' },
      { label: 'Low sulphur', value_name: 'lowsulfur' },
    ],
    seriesKey: 'seriesMarineFuel',
    frequency: 'Daily',
  },
  {
    section: 'shipping',
    title: 'Freight costs for shipping oil',
    id: 'datawrapper-chart-CwGjy',
    src: 'https://datawrapper.dwcdn.net/CwGjy',
    meta: [
      { label: 'Dirty tankers', value_name: 'dirty_tanker' },
      { label: ' Clean tankers', value_name: 'clean_tanker' },
    ],
    seriesKey: 'seriesFreightOil',
    frequency: 'Daily',
    enabled: true,
  },
  {
    section: 'shipping',
    title: 'Freight costs for containers and bulk',
    id: 'datawrapper-chart-RY0Fg',
    src: 'https://datawrapper.dwcdn.net/RY0Fg',
    meta: [
      { label: 'Containers', value_name: 'containers' },
      { label: ' Bulk', value_name: 'bulk' },
    ],
    seriesKey: 'seriesFreightContainerBulk',
    frequency: 'Weekly',
    enabled: true,
  },
  {
    section: 'food',
    title: 'FAO Food Price Index',
    id: 'datawrapper-chart-3spao',
    src: 'https://datawrapper.dwcdn.net/3spao',
    meta: [{ label: 'FAO Food Price Index', value_name: 'value' }],
    seriesKey: 'seriesFaoFoodPriceIndex',
    frequency: 'Monthly',
  },
  {
    section: 'food',
    title: 'Commodity food prices',
    id: 'datawrapper-chart-xe9L9',
    src: 'https://datawrapper.dwcdn.net/xe9L9',
    meta: [{ label: 'Agricultural and Livestock Index', value_name: 'index' }],
    seriesKey: 'seriesWheatAgriculture',
    frequency: 'Daily',
  },
  {
    section: 'food',
    title: 'Fertilizer prices',
    id: 'datawrapper-chart-E2VH4',
    src: 'https://datawrapper.dwcdn.net/E2VH4',
    meta: [
      { label: 'Diammonium Phosphate', value_name: 'diammonium' },
      { label: 'Urea', value_name: 'urea' },
    ],
    seriesKey: 'seriesWBFertilizerIndex',
    frequency: 'Weekly',
  },
  {
    section: 'food',
    title: 'Food price inflation',
    id: 'datawrapper-chart-pKWw6',
    src: 'https://datawrapper.dwcdn.net/pKWw6',
    meta: [{ label: 'Developing economies', value_name: 'med_developing' }],
    seriesKey: 'seriesFoodPriceInflation',
    frequency: 'Monthly',
    methodology: 'Data on year-on-year monthly food price inflation based on consumer price subindices across 139 countries. UN country group classifications. Group aggregates represent median values, with latest data points used when 80% of countries in the group have data available.',
  },
  {
    section: 'energy',
    title: 'Oil prices',
    id: 'datawrapper-chart-EYPxo',
    src: 'https://datawrapper.dwcdn.net/EYPxo',
    meta: [
      { label: 'Europe', value_name: 'europe' },
      { label: 'Middle East', value_name: 'middleeast' },
      { label: 'Russian Federation', value_name: 'russia' },
    ],
    seriesKey: 'seriesEnergy',
    frequency: 'Daily',
  },
  {
    section: 'energy',
    title: 'Natural gas prices',
    id: 'datawrapper-chart-6oB41',
    src: 'https://datawrapper.dwcdn.net/6oB41',
    meta: [
      { label: 'Asia', value_name: 'asia' },
      { label: 'Europe', value_name: 'europe' },
      { label: 'North America', value_name: 'us' },
    ],
    seriesKey: 'seriesNaturalgasPrices',
    frequency: 'Daily',
  },
  {
    section: 'energy',
    title: 'Petroleum gas prices',
    id: 'datawrapper-chart-74dPn',
    src: 'https://datawrapper.dwcdn.net/74dPn',
    meta: [
      { label: 'Middle East', value_name: 'pro_middleeast' },
      { label: 'Europe', value_name: 'pro_europe' },
      { label: 'North America', value_name: 'pro_america' },
    ],
    seriesKey: 'seriesPetroleumgasPrices',
    frequency: 'Weekly',
  },
  {
    section: 'energy',
    title: 'Biofuel prices',
    id: 'datawrapper-chart-awQuD',
    src: 'https://datawrapper.dwcdn.net/awQuD',
    meta: [{ label: 'Biofuel', value_name: 'biofuels' }],
    seriesKey: 'serieBiofuelPrices',
    frequency: 'Daily',
  },
  {
    section: 'finance',
    title: 'Exchange rates',
    id: 'datawrapper-chart-69yXd',
    src: 'https://datawrapper.dwcdn.net/69yXd',
    meta: [
      { label: 'Africa', value_name: 'Africa' },
      { label: 'Developing Asia and Oceania', value_name: 'Asia' },
      { label: 'Latin America and the Caribbean', value_name: 'America' },
    ],
    seriesKey: 'seriesExchangeRates',
    frequency: 'Daily',
    methodology: 'Data on daily exchange rate of 139 currencies against the US Dollar. UN country group classifications. Group aggregates represent the median value.',
  },
  {
    section: 'finance',
    title: 'Stock prices',
    id: 'datawrapper-chart-u7z7Q',
    src: 'https://datawrapper.dwcdn.net/u7z7Q',
    meta: [{ label: 'Emerging economies', value_name: 'emerging' }],
    seriesKey: 'seriesStockPrices',
    frequency: 'Daily',
  },
  {
    section: 'finance',
    title: 'International reserves',
    id: 'datawrapper-chart-r91nz',
    src: 'https://datawrapper.dwcdn.net/r91nz',
    meta: [
      { label: 'Africa', value_name: 'Africa' },
      { label: 'Developing Asia and Oceania', value_name: 'Asia' },
      { label: 'Latin America and the Caribbean', value_name: 'America' },
    ],
    seriesKey: 'seriesInternationalReserves',
    frequency: 'Monthly',
    methodology: 'Data on international reserves for 189 economies. UN country group classifications. Group aggregates are the total sum of reserves, with latest data points used when 80% of countries in the group have data available.',
  },
  {
    section: 'finance',
    title: 'Inflation',
    id: 'datawrapper-chart-HJO3x',
    src: 'https://datawrapper.dwcdn.net/HJO3x',
    meta: [{ label: 'Developing economies', value_name: 'med_developing' }],
    seriesKey: 'seriesInflationRegion',
    frequency: 'Monthly',
    methodology: 'Data on monthly inflation rates of 163 economies. UN country group classifications. Group aggregates represent the median value, with latest data points used when 80% of countries in the group have data available.',
  },
];

export default dashboardCharts;
